name: ساخت APK با Flet

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: دریافت کد
      uses: actions/checkout@v4

    - name: نصب Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: نصب وابستگی‌های سیستم
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk android-sdk curl git unzip xz-utils zip libglu1-mesa

    - name: تنظیم متغیرهای محیطی JDK و SDK
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV

    - name: نصب Flutter SDK
      run: |
        cd /opt
        sudo git clone https://github.com/flutter/flutter.git -b stable
        sudo chmod -R 777 /opt/flutter
        echo "/opt/flutter/bin" >> $GITHUB_PATH
        echo "FLUTTER_ROOT=/opt/flutter" >> $GITHUB_ENV

    - name: بررسی نصب Flutter
      run: |
        export PATH="$PATH:/opt/flutter/bin"
        flutter --version
        flutter doctor --android-licenses -y || true
        echo "y" | flutter doctor --android-licenses || true

    - name: نصب Flet و وابستگی‌ها
      run: |
        python -m pip install --upgrade pip
        pip install flet
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: تنظیم مجوز اجرایی برای فایل Xray در اندروید
      run: |
        if [ -f core/android/xray ]; then
          chmod +x core/android/xray
          echo "مجوز اجرایی برای xray تنظیم شد."
        else
          echo "فایل xray در مسیر core/android/ پیدا نشد!"
          exit 1
        fi

    - name: ساخت APK با Flet (غیرتعاملی)
      run: |
        export PATH="$PATH:/opt/flutter/bin"
        export FLUTTER_ROOT="/opt/flutter"
        echo "y" | flet build apk --verbose || true

    - name: آپلود APK
      uses: actions/upload-artifact@v4
      with:
        name: Vpn-App-APK
        path: build/apk/*.apk
